spring:
  data:
#    mongodb:
#      uri: mongodb://xinyongjin:eGlueW9uZ2ppbgo=@221.228.75.188:27010/xinyongjin
    redis:
      database: 0
      hostName: 172.16.20.205
      port: 6379
      password: null
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
      timeout: 0