spring:
  #mongodb
  data: 
     mongodb: 
       uri: mongodb://xinyongjin:eGlueW9uZ2ppbgo=@172.16.20.69:27017,172.16.20.205:27017,172.16.20.72:27017/xinyongjin
  # Redis 
  redis: 
    database: 0  
    # Redis服务器地址
    hostName: 172.16.20.205
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:   
    # 连接池最大连接数（使用负值表示没有限制）
    pool: 
      max-active: 8  
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1  
      # 连接池中的最大空闲连接
      max-idle: 8  
      # 连接池中的最小空闲连接
      min-idle: 0  
    # 连接超时时间（毫秒）
    timeout: 0          
