spring:
  application:
    name: MA
  #mysql durid data source  
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.16.20.205:3306/ma
      username: finance
      password: 123456
      #下面为连接池的补充设置，应用到上面所有数据源中
      #初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      #配置获取连接等待超时的时间
      maxWait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒 
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #打开PSCache，并且指定每个连接上PSCache的大小 
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙 
      filters: stat,wall,log4j
      #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000
      #合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true  
  #mongodb    
  data: 
     mongodb: 
       uri: mongodb://xinyongjin:eGlueW9uZ2ppbgo=@172.16.20.205:27017/xinyongjin
  # Redis 
  redis: 
    database: 0  
    # Redis服务器地址
    hostName: 180.101.195.217
    # Redis服务器连接端口
    port: 5020
    # Redis服务器连接密码（默认为空）
    password: eoeHle9twnlrefqewwudgkecxfp.ae
    # 连接池最大连接数（使用负值表示没有限制）
    pool: 
      max_active: 10
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max_wait: -1
      # 连接池中的最大空闲连接
      max_idle: 8
      # 连接池中的最小空闲连接
      min_idle: 0
    # 连接超时时间（毫秒）
    timeout: 30001
 
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.daikuan.platform.ma.pojo
  config-location: classpath:mybatis-config.xml

rocketMQ: 
  namesrvAddr: 172.16.20.69:9876