// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: attribute.proto

package demo.ProtocolBuffer;

public final class CustomerCreditDataProto {
  private CustomerCreditDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CustomerCreditDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string psptId = 1;
    /**
     * <code>required string psptId = 1;</code>
     *
     * <pre>
     *证件号码；
     * </pre>
     */
    boolean hasPsptId();
    /**
     * <code>required string psptId = 1;</code>
     *
     * <pre>
     *证件号码；
     * </pre>
     */
    java.lang.String getPsptId();
    /**
     * <code>required string psptId = 1;</code>
     *
     * <pre>
     *证件号码；
     * </pre>
     */
    com.google.protobuf.ByteString
        getPsptIdBytes();

    // required string msisdn = 2;
    /**
     * <code>required string msisdn = 2;</code>
     *
     * <pre>
     *手机号码
     * </pre>
     */
    boolean hasMsisdn();
    /**
     * <code>required string msisdn = 2;</code>
     *
     * <pre>
     *手机号码
     * </pre>
     */
    java.lang.String getMsisdn();
    /**
     * <code>required string msisdn = 2;</code>
     *
     * <pre>
     *手机号码
     * </pre>
     */
    com.google.protobuf.ByteString
        getMsisdnBytes();

    // required string customerLevel = 3;
    /**
     * <code>required string customerLevel = 3;</code>
     *
     * <pre>
     *用户等级
     * </pre>
     */
    boolean hasCustomerLevel();
    /**
     * <code>required string customerLevel = 3;</code>
     *
     * <pre>
     *用户等级
     * </pre>
     */
    java.lang.String getCustomerLevel();
    /**
     * <code>required string customerLevel = 3;</code>
     *
     * <pre>
     *用户等级
     * </pre>
     */
    com.google.protobuf.ByteString
        getCustomerLevelBytes();

    // required int32 customerAttribue = 4;
    /**
     * <code>required int32 customerAttribue = 4;</code>
     *
     * <pre>
     *客户属性
     * </pre>
     */
    boolean hasCustomerAttribue();
    /**
     * <code>required int32 customerAttribue = 4;</code>
     *
     * <pre>
     *客户属性
     * </pre>
     */
    int getCustomerAttribue();

    // required int32 innetDuaration = 5;
    /**
     * <code>required int32 innetDuaration = 5;</code>
     *
     * <pre>
     *在网时间，单位：月    
     * </pre>
     */
    boolean hasInnetDuaration();
    /**
     * <code>required int32 innetDuaration = 5;</code>
     *
     * <pre>
     *在网时间，单位：月    
     * </pre>
     */
    int getInnetDuaration();

    // required int32 msisdnAmount = 6;
    /**
     * <code>required int32 msisdnAmount = 6;</code>
     *
     * <pre>
     *身份证所匹配手机号码数量；
     * </pre>
     */
    boolean hasMsisdnAmount();
    /**
     * <code>required int32 msisdnAmount = 6;</code>
     *
     * <pre>
     *身份证所匹配手机号码数量；
     * </pre>
     */
    int getMsisdnAmount();

    // required int32 sixMonthFee = 7;
    /**
     * <code>required int32 sixMonthFee = 7;</code>
     *
     * <pre>
     *近六个月月均消费额，单位:分
     * </pre>
     */
    boolean hasSixMonthFee();
    /**
     * <code>required int32 sixMonthFee = 7;</code>
     *
     * <pre>
     *近六个月月均消费额，单位:分
     * </pre>
     */
    int getSixMonthFee();

    // required int32 oweTimes = 8;
    /**
     * <code>required int32 oweTimes = 8;</code>
     *
     * <pre>
     *近六个月内逾期欠费次数
     * </pre>
     */
    boolean hasOweTimes();
    /**
     * <code>required int32 oweTimes = 8;</code>
     *
     * <pre>
     *近六个月内逾期欠费次数
     * </pre>
     */
    int getOweTimes();

    // required int32 expireFlag = 9;
    /**
     * <code>required int32 expireFlag = 9;</code>
     *
     * <pre>
     *当前是否逾期欠费
     * </pre>
     */
    boolean hasExpireFlag();
    /**
     * <code>required int32 expireFlag = 9;</code>
     *
     * <pre>
     *当前是否逾期欠费
     * </pre>
     */
    int getExpireFlag();

    // required int32 roamFlagOneYear = 10;
    /**
     * <code>required int32 roamFlagOneYear = 10;</code>
     *
     * <pre>
     *近1年内是否有境外漫游记录
     * </pre>
     */
    boolean hasRoamFlagOneYear();
    /**
     * <code>required int32 roamFlagOneYear = 10;</code>
     *
     * <pre>
     *近1年内是否有境外漫游记录
     * </pre>
     */
    int getRoamFlagOneYear();

    // required int32 contractTimes = 11;
    /**
     * <code>required int32 contractTimes = 11;</code>
     *
     * <pre>
     *与指定号码联系次数；
     * </pre>
     */
    boolean hasContractTimes();
    /**
     * <code>required int32 contractTimes = 11;</code>
     *
     * <pre>
     *与指定号码联系次数；
     * </pre>
     */
    int getContractTimes();

    // required int32 callPlace = 12;
    /**
     * <code>required int32 callPlace = 12;</code>
     *
     * <pre>
     *白天常用通话地区,维表方式提供
     * </pre>
     */
    boolean hasCallPlace();
    /**
     * <code>required int32 callPlace = 12;</code>
     *
     * <pre>
     *白天常用通话地区,维表方式提供
     * </pre>
     */
    int getCallPlace();

    // required int32 receiveSMSTimes = 13;
    /**
     * <code>required int32 receiveSMSTimes = 13;</code>
     *
     * <pre>
     * 指定号码短信接受次数
     * </pre>
     */
    boolean hasReceiveSMSTimes();
    /**
     * <code>required int32 receiveSMSTimes = 13;</code>
     *
     * <pre>
     * 指定号码短信接受次数
     * </pre>
     */
    int getReceiveSMSTimes();

    // required int32 groupFlag = 14;
    /**
     * <code>required int32 groupFlag = 14;</code>
     *
     * <pre>
     * 是否为联通集团客户
     * </pre>
     */
    boolean hasGroupFlag();
    /**
     * <code>required int32 groupFlag = 14;</code>
     *
     * <pre>
     * 是否为联通集团客户
     * </pre>
     */
    int getGroupFlag();

    // required string billAddress = 15;
    /**
     * <code>required string billAddress = 15;</code>
     *
     * <pre>
     * 联通账单地址
     * </pre>
     */
    boolean hasBillAddress();
    /**
     * <code>required string billAddress = 15;</code>
     *
     * <pre>
     * 联通账单地址
     * </pre>
     */
    java.lang.String getBillAddress();
    /**
     * <code>required string billAddress = 15;</code>
     *
     * <pre>
     * 联通账单地址
     * </pre>
     */
    com.google.protobuf.ByteString
        getBillAddressBytes();

    // required int32 CustomerFeeFlag = 16;
    /**
     * <code>required int32 CustomerFeeFlag = 16;</code>
     *
     * <pre>
     * 客户属性标识
     * </pre>
     */
    boolean hasCustomerFeeFlag();
    /**
     * <code>required int32 CustomerFeeFlag = 16;</code>
     *
     * <pre>
     * 客户属性标识
     * </pre>
     */
    int getCustomerFeeFlag();

    // required int32 totalGrade = 17;
    /**
     * <code>required int32 totalGrade = 17;</code>
     *
     * <pre>
     *总评分
     * </pre>
     */
    boolean hasTotalGrade();
    /**
     * <code>required int32 totalGrade = 17;</code>
     *
     * <pre>
     *总评分
     * </pre>
     */
    int getTotalGrade();

    // required int32 teleGrade = 18;
    /**
     * <code>required int32 teleGrade = 18;</code>
     *
     * <pre>
     *通信业务特征评分
     * </pre>
     */
    boolean hasTeleGrade();
    /**
     * <code>required int32 teleGrade = 18;</code>
     *
     * <pre>
     *通信业务特征评分
     * </pre>
     */
    int getTeleGrade();

    // required int32 basicAttriGrade = 19;
    /**
     * <code>required int32 basicAttriGrade = 19;</code>
     *
     * <pre>
     *用户基本特征评分
     * </pre>
     */
    boolean hasBasicAttriGrade();
    /**
     * <code>required int32 basicAttriGrade = 19;</code>
     *
     * <pre>
     *用户基本特征评分
     * </pre>
     */
    int getBasicAttriGrade();

    // required int32 behaviorGrade = 20;
    /**
     * <code>required int32 behaviorGrade = 20;</code>
     *
     * <pre>
     *用户行为特征评分
     * </pre>
     */
    boolean hasBehaviorGrade();
    /**
     * <code>required int32 behaviorGrade = 20;</code>
     *
     * <pre>
     *用户行为特征评分
     * </pre>
     */
    int getBehaviorGrade();

    // required int32 creditRelatGrade = 21;
    /**
     * <code>required int32 creditRelatGrade = 21;</code>
     *
     * <pre>
     *信用关联特征的评分
     * </pre>
     */
    boolean hasCreditRelatGrade();
    /**
     * <code>required int32 creditRelatGrade = 21;</code>
     *
     * <pre>
     *信用关联特征的评分
     * </pre>
     */
    int getCreditRelatGrade();

    // required int32 protocolType = 22;
    /**
     * <code>required int32 protocolType = 22;</code>
     *
     * <pre>
     * 协议类型
     * </pre>
     */
    boolean hasProtocolType();
    /**
     * <code>required int32 protocolType = 22;</code>
     *
     * <pre>
     * 协议类型
     * </pre>
     */
    int getProtocolType();

    // required int32 contactAmount = 23;
    /**
     * <code>required int32 contactAmount = 23;</code>
     *
     * <pre>
     * 前一个月呼入及呼出联络圈
     * </pre>
     */
    boolean hasContactAmount();
    /**
     * <code>required int32 contactAmount = 23;</code>
     *
     * <pre>
     * 前一个月呼入及呼出联络圈
     * </pre>
     */
    int getContactAmount();
  }
  /**
   * Protobuf type {@code CustomerCreditData}
   */
  public static final class CustomerCreditData extends
      com.google.protobuf.GeneratedMessage
      implements CustomerCreditDataOrBuilder {
    // Use CustomerCreditData.newBuilder() to construct.
    private CustomerCreditData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CustomerCreditData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CustomerCreditData defaultInstance;
    public static CustomerCreditData getDefaultInstance() {
      return defaultInstance;
    }

    public CustomerCreditData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CustomerCreditData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              psptId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              msisdn_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              customerLevel_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              customerAttribue_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              innetDuaration_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              msisdnAmount_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              sixMonthFee_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              oweTimes_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              expireFlag_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              roamFlagOneYear_ = input.readInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              contractTimes_ = input.readInt32();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              callPlace_ = input.readInt32();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              receiveSMSTimes_ = input.readInt32();
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              groupFlag_ = input.readInt32();
              break;
            }
            case 122: {
              bitField0_ |= 0x00004000;
              billAddress_ = input.readBytes();
              break;
            }
            case 128: {
              bitField0_ |= 0x00008000;
              customerFeeFlag_ = input.readInt32();
              break;
            }
            case 136: {
              bitField0_ |= 0x00010000;
              totalGrade_ = input.readInt32();
              break;
            }
            case 144: {
              bitField0_ |= 0x00020000;
              teleGrade_ = input.readInt32();
              break;
            }
            case 152: {
              bitField0_ |= 0x00040000;
              basicAttriGrade_ = input.readInt32();
              break;
            }
            case 160: {
              bitField0_ |= 0x00080000;
              behaviorGrade_ = input.readInt32();
              break;
            }
            case 168: {
              bitField0_ |= 0x00100000;
              creditRelatGrade_ = input.readInt32();
              break;
            }
            case 176: {
              bitField0_ |= 0x00200000;
              protocolType_ = input.readInt32();
              break;
            }
            case 184: {
              bitField0_ |= 0x00400000;
              contactAmount_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CustomerCreditDataProto.internal_static_CustomerCreditData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CustomerCreditDataProto.internal_static_CustomerCreditData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CustomerCreditDataProto.CustomerCreditData.class, CustomerCreditDataProto.CustomerCreditData.Builder.class);
    }

    public static com.google.protobuf.Parser<CustomerCreditData> PARSER =
        new com.google.protobuf.AbstractParser<CustomerCreditData>() {
      public CustomerCreditData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CustomerCreditData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CustomerCreditData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string psptId = 1;
    public static final int PSPTID_FIELD_NUMBER = 1;
    private java.lang.Object psptId_;
    /**
     * <code>required string psptId = 1;</code>
     *
     * <pre>
     *证件号码；
     * </pre>
     */
    public boolean hasPsptId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string psptId = 1;</code>
     *
     * <pre>
     *证件号码；
     * </pre>
     */
    public java.lang.String getPsptId() {
      java.lang.Object ref = psptId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          psptId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string psptId = 1;</code>
     *
     * <pre>
     *证件号码；
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPsptIdBytes() {
      java.lang.Object ref = psptId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        psptId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string msisdn = 2;
    public static final int MSISDN_FIELD_NUMBER = 2;
    private java.lang.Object msisdn_;
    /**
     * <code>required string msisdn = 2;</code>
     *
     * <pre>
     *手机号码
     * </pre>
     */
    public boolean hasMsisdn() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string msisdn = 2;</code>
     *
     * <pre>
     *手机号码
     * </pre>
     */
    public java.lang.String getMsisdn() {
      java.lang.Object ref = msisdn_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msisdn_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string msisdn = 2;</code>
     *
     * <pre>
     *手机号码
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMsisdnBytes() {
      java.lang.Object ref = msisdn_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msisdn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string customerLevel = 3;
    public static final int CUSTOMERLEVEL_FIELD_NUMBER = 3;
    private java.lang.Object customerLevel_;
    /**
     * <code>required string customerLevel = 3;</code>
     *
     * <pre>
     *用户等级
     * </pre>
     */
    public boolean hasCustomerLevel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string customerLevel = 3;</code>
     *
     * <pre>
     *用户等级
     * </pre>
     */
    public java.lang.String getCustomerLevel() {
      java.lang.Object ref = customerLevel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          customerLevel_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string customerLevel = 3;</code>
     *
     * <pre>
     *用户等级
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCustomerLevelBytes() {
      java.lang.Object ref = customerLevel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customerLevel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 customerAttribue = 4;
    public static final int CUSTOMERATTRIBUE_FIELD_NUMBER = 4;
    private int customerAttribue_;
    /**
     * <code>required int32 customerAttribue = 4;</code>
     *
     * <pre>
     *客户属性
     * </pre>
     */
    public boolean hasCustomerAttribue() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 customerAttribue = 4;</code>
     *
     * <pre>
     *客户属性
     * </pre>
     */
    public int getCustomerAttribue() {
      return customerAttribue_;
    }

    // required int32 innetDuaration = 5;
    public static final int INNETDUARATION_FIELD_NUMBER = 5;
    private int innetDuaration_;
    /**
     * <code>required int32 innetDuaration = 5;</code>
     *
     * <pre>
     *在网时间，单位：月    
     * </pre>
     */
    public boolean hasInnetDuaration() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 innetDuaration = 5;</code>
     *
     * <pre>
     *在网时间，单位：月    
     * </pre>
     */
    public int getInnetDuaration() {
      return innetDuaration_;
    }

    // required int32 msisdnAmount = 6;
    public static final int MSISDNAMOUNT_FIELD_NUMBER = 6;
    private int msisdnAmount_;
    /**
     * <code>required int32 msisdnAmount = 6;</code>
     *
     * <pre>
     *身份证所匹配手机号码数量；
     * </pre>
     */
    public boolean hasMsisdnAmount() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 msisdnAmount = 6;</code>
     *
     * <pre>
     *身份证所匹配手机号码数量；
     * </pre>
     */
    public int getMsisdnAmount() {
      return msisdnAmount_;
    }

    // required int32 sixMonthFee = 7;
    public static final int SIXMONTHFEE_FIELD_NUMBER = 7;
    private int sixMonthFee_;
    /**
     * <code>required int32 sixMonthFee = 7;</code>
     *
     * <pre>
     *近六个月月均消费额，单位:分
     * </pre>
     */
    public boolean hasSixMonthFee() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required int32 sixMonthFee = 7;</code>
     *
     * <pre>
     *近六个月月均消费额，单位:分
     * </pre>
     */
    public int getSixMonthFee() {
      return sixMonthFee_;
    }

    // required int32 oweTimes = 8;
    public static final int OWETIMES_FIELD_NUMBER = 8;
    private int oweTimes_;
    /**
     * <code>required int32 oweTimes = 8;</code>
     *
     * <pre>
     *近六个月内逾期欠费次数
     * </pre>
     */
    public boolean hasOweTimes() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required int32 oweTimes = 8;</code>
     *
     * <pre>
     *近六个月内逾期欠费次数
     * </pre>
     */
    public int getOweTimes() {
      return oweTimes_;
    }

    // required int32 expireFlag = 9;
    public static final int EXPIREFLAG_FIELD_NUMBER = 9;
    private int expireFlag_;
    /**
     * <code>required int32 expireFlag = 9;</code>
     *
     * <pre>
     *当前是否逾期欠费
     * </pre>
     */
    public boolean hasExpireFlag() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required int32 expireFlag = 9;</code>
     *
     * <pre>
     *当前是否逾期欠费
     * </pre>
     */
    public int getExpireFlag() {
      return expireFlag_;
    }

    // required int32 roamFlagOneYear = 10;
    public static final int ROAMFLAGONEYEAR_FIELD_NUMBER = 10;
    private int roamFlagOneYear_;
    /**
     * <code>required int32 roamFlagOneYear = 10;</code>
     *
     * <pre>
     *近1年内是否有境外漫游记录
     * </pre>
     */
    public boolean hasRoamFlagOneYear() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>required int32 roamFlagOneYear = 10;</code>
     *
     * <pre>
     *近1年内是否有境外漫游记录
     * </pre>
     */
    public int getRoamFlagOneYear() {
      return roamFlagOneYear_;
    }

    // required int32 contractTimes = 11;
    public static final int CONTRACTTIMES_FIELD_NUMBER = 11;
    private int contractTimes_;
    /**
     * <code>required int32 contractTimes = 11;</code>
     *
     * <pre>
     *与指定号码联系次数；
     * </pre>
     */
    public boolean hasContractTimes() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>required int32 contractTimes = 11;</code>
     *
     * <pre>
     *与指定号码联系次数；
     * </pre>
     */
    public int getContractTimes() {
      return contractTimes_;
    }

    // required int32 callPlace = 12;
    public static final int CALLPLACE_FIELD_NUMBER = 12;
    private int callPlace_;
    /**
     * <code>required int32 callPlace = 12;</code>
     *
     * <pre>
     *白天常用通话地区,维表方式提供
     * </pre>
     */
    public boolean hasCallPlace() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>required int32 callPlace = 12;</code>
     *
     * <pre>
     *白天常用通话地区,维表方式提供
     * </pre>
     */
    public int getCallPlace() {
      return callPlace_;
    }

    // required int32 receiveSMSTimes = 13;
    public static final int RECEIVESMSTIMES_FIELD_NUMBER = 13;
    private int receiveSMSTimes_;
    /**
     * <code>required int32 receiveSMSTimes = 13;</code>
     *
     * <pre>
     * 指定号码短信接受次数
     * </pre>
     */
    public boolean hasReceiveSMSTimes() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>required int32 receiveSMSTimes = 13;</code>
     *
     * <pre>
     * 指定号码短信接受次数
     * </pre>
     */
    public int getReceiveSMSTimes() {
      return receiveSMSTimes_;
    }

    // required int32 groupFlag = 14;
    public static final int GROUPFLAG_FIELD_NUMBER = 14;
    private int groupFlag_;
    /**
     * <code>required int32 groupFlag = 14;</code>
     *
     * <pre>
     * 是否为联通集团客户
     * </pre>
     */
    public boolean hasGroupFlag() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>required int32 groupFlag = 14;</code>
     *
     * <pre>
     * 是否为联通集团客户
     * </pre>
     */
    public int getGroupFlag() {
      return groupFlag_;
    }

    // required string billAddress = 15;
    public static final int BILLADDRESS_FIELD_NUMBER = 15;
    private java.lang.Object billAddress_;
    /**
     * <code>required string billAddress = 15;</code>
     *
     * <pre>
     * 联通账单地址
     * </pre>
     */
    public boolean hasBillAddress() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>required string billAddress = 15;</code>
     *
     * <pre>
     * 联通账单地址
     * </pre>
     */
    public java.lang.String getBillAddress() {
      java.lang.Object ref = billAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          billAddress_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string billAddress = 15;</code>
     *
     * <pre>
     * 联通账单地址
     * </pre>
     */
    public com.google.protobuf.ByteString
        getBillAddressBytes() {
      java.lang.Object ref = billAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        billAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 CustomerFeeFlag = 16;
    public static final int CUSTOMERFEEFLAG_FIELD_NUMBER = 16;
    private int customerFeeFlag_;
    /**
     * <code>required int32 CustomerFeeFlag = 16;</code>
     *
     * <pre>
     * 客户属性标识
     * </pre>
     */
    public boolean hasCustomerFeeFlag() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    /**
     * <code>required int32 CustomerFeeFlag = 16;</code>
     *
     * <pre>
     * 客户属性标识
     * </pre>
     */
    public int getCustomerFeeFlag() {
      return customerFeeFlag_;
    }

    // required int32 totalGrade = 17;
    public static final int TOTALGRADE_FIELD_NUMBER = 17;
    private int totalGrade_;
    /**
     * <code>required int32 totalGrade = 17;</code>
     *
     * <pre>
     *总评分
     * </pre>
     */
    public boolean hasTotalGrade() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    /**
     * <code>required int32 totalGrade = 17;</code>
     *
     * <pre>
     *总评分
     * </pre>
     */
    public int getTotalGrade() {
      return totalGrade_;
    }

    // required int32 teleGrade = 18;
    public static final int TELEGRADE_FIELD_NUMBER = 18;
    private int teleGrade_;
    /**
     * <code>required int32 teleGrade = 18;</code>
     *
     * <pre>
     *通信业务特征评分
     * </pre>
     */
    public boolean hasTeleGrade() {
      return ((bitField0_ & 0x00020000) == 0x00020000);
    }
    /**
     * <code>required int32 teleGrade = 18;</code>
     *
     * <pre>
     *通信业务特征评分
     * </pre>
     */
    public int getTeleGrade() {
      return teleGrade_;
    }

    // required int32 basicAttriGrade = 19;
    public static final int BASICATTRIGRADE_FIELD_NUMBER = 19;
    private int basicAttriGrade_;
    /**
     * <code>required int32 basicAttriGrade = 19;</code>
     *
     * <pre>
     *用户基本特征评分
     * </pre>
     */
    public boolean hasBasicAttriGrade() {
      return ((bitField0_ & 0x00040000) == 0x00040000);
    }
    /**
     * <code>required int32 basicAttriGrade = 19;</code>
     *
     * <pre>
     *用户基本特征评分
     * </pre>
     */
    public int getBasicAttriGrade() {
      return basicAttriGrade_;
    }

    // required int32 behaviorGrade = 20;
    public static final int BEHAVIORGRADE_FIELD_NUMBER = 20;
    private int behaviorGrade_;
    /**
     * <code>required int32 behaviorGrade = 20;</code>
     *
     * <pre>
     *用户行为特征评分
     * </pre>
     */
    public boolean hasBehaviorGrade() {
      return ((bitField0_ & 0x00080000) == 0x00080000);
    }
    /**
     * <code>required int32 behaviorGrade = 20;</code>
     *
     * <pre>
     *用户行为特征评分
     * </pre>
     */
    public int getBehaviorGrade() {
      return behaviorGrade_;
    }

    // required int32 creditRelatGrade = 21;
    public static final int CREDITRELATGRADE_FIELD_NUMBER = 21;
    private int creditRelatGrade_;
    /**
     * <code>required int32 creditRelatGrade = 21;</code>
     *
     * <pre>
     *信用关联特征的评分
     * </pre>
     */
    public boolean hasCreditRelatGrade() {
      return ((bitField0_ & 0x00100000) == 0x00100000);
    }
    /**
     * <code>required int32 creditRelatGrade = 21;</code>
     *
     * <pre>
     *信用关联特征的评分
     * </pre>
     */
    public int getCreditRelatGrade() {
      return creditRelatGrade_;
    }

    // required int32 protocolType = 22;
    public static final int PROTOCOLTYPE_FIELD_NUMBER = 22;
    private int protocolType_;
    /**
     * <code>required int32 protocolType = 22;</code>
     *
     * <pre>
     * 协议类型
     * </pre>
     */
    public boolean hasProtocolType() {
      return ((bitField0_ & 0x00200000) == 0x00200000);
    }
    /**
     * <code>required int32 protocolType = 22;</code>
     *
     * <pre>
     * 协议类型
     * </pre>
     */
    public int getProtocolType() {
      return protocolType_;
    }

    // required int32 contactAmount = 23;
    public static final int CONTACTAMOUNT_FIELD_NUMBER = 23;
    private int contactAmount_;
    /**
     * <code>required int32 contactAmount = 23;</code>
     *
     * <pre>
     * 前一个月呼入及呼出联络圈
     * </pre>
     */
    public boolean hasContactAmount() {
      return ((bitField0_ & 0x00400000) == 0x00400000);
    }
    /**
     * <code>required int32 contactAmount = 23;</code>
     *
     * <pre>
     * 前一个月呼入及呼出联络圈
     * </pre>
     */
    public int getContactAmount() {
      return contactAmount_;
    }

    private void initFields() {
      psptId_ = "";
      msisdn_ = "";
      customerLevel_ = "";
      customerAttribue_ = 0;
      innetDuaration_ = 0;
      msisdnAmount_ = 0;
      sixMonthFee_ = 0;
      oweTimes_ = 0;
      expireFlag_ = 0;
      roamFlagOneYear_ = 0;
      contractTimes_ = 0;
      callPlace_ = 0;
      receiveSMSTimes_ = 0;
      groupFlag_ = 0;
      billAddress_ = "";
      customerFeeFlag_ = 0;
      totalGrade_ = 0;
      teleGrade_ = 0;
      basicAttriGrade_ = 0;
      behaviorGrade_ = 0;
      creditRelatGrade_ = 0;
      protocolType_ = 0;
      contactAmount_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPsptId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsisdn()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCustomerLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCustomerAttribue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInnetDuaration()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsisdnAmount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSixMonthFee()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOweTimes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasExpireFlag()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRoamFlagOneYear()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContractTimes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCallPlace()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReceiveSMSTimes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGroupFlag()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBillAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCustomerFeeFlag()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTotalGrade()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTeleGrade()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBasicAttriGrade()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBehaviorGrade()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreditRelatGrade()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProtocolType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContactAmount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPsptIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMsisdnBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getCustomerLevelBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, customerAttribue_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, innetDuaration_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, msisdnAmount_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, sixMonthFee_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, oweTimes_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, expireFlag_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, roamFlagOneYear_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(11, contractTimes_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(12, callPlace_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt32(13, receiveSMSTimes_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeInt32(14, groupFlag_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeBytes(15, getBillAddressBytes());
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeInt32(16, customerFeeFlag_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeInt32(17, totalGrade_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        output.writeInt32(18, teleGrade_);
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        output.writeInt32(19, basicAttriGrade_);
      }
      if (((bitField0_ & 0x00080000) == 0x00080000)) {
        output.writeInt32(20, behaviorGrade_);
      }
      if (((bitField0_ & 0x00100000) == 0x00100000)) {
        output.writeInt32(21, creditRelatGrade_);
      }
      if (((bitField0_ & 0x00200000) == 0x00200000)) {
        output.writeInt32(22, protocolType_);
      }
      if (((bitField0_ & 0x00400000) == 0x00400000)) {
        output.writeInt32(23, contactAmount_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPsptIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMsisdnBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getCustomerLevelBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, customerAttribue_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, innetDuaration_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, msisdnAmount_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, sixMonthFee_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, oweTimes_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, expireFlag_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, roamFlagOneYear_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, contractTimes_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, callPlace_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, receiveSMSTimes_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, groupFlag_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(15, getBillAddressBytes());
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(16, customerFeeFlag_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(17, totalGrade_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(18, teleGrade_);
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(19, basicAttriGrade_);
      }
      if (((bitField0_ & 0x00080000) == 0x00080000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(20, behaviorGrade_);
      }
      if (((bitField0_ & 0x00100000) == 0x00100000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(21, creditRelatGrade_);
      }
      if (((bitField0_ & 0x00200000) == 0x00200000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(22, protocolType_);
      }
      if (((bitField0_ & 0x00400000) == 0x00400000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(23, contactAmount_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static CustomerCreditDataProto.CustomerCreditData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CustomerCreditDataProto.CustomerCreditData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CustomerCreditDataProto.CustomerCreditData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CustomerCreditDataProto.CustomerCreditData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CustomerCreditDataProto.CustomerCreditData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CustomerCreditDataProto.CustomerCreditData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static CustomerCreditDataProto.CustomerCreditData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static CustomerCreditDataProto.CustomerCreditData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static CustomerCreditDataProto.CustomerCreditData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CustomerCreditDataProto.CustomerCreditData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(CustomerCreditDataProto.CustomerCreditData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CustomerCreditData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements CustomerCreditDataProto.CustomerCreditDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CustomerCreditDataProto.internal_static_CustomerCreditData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CustomerCreditDataProto.internal_static_CustomerCreditData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CustomerCreditDataProto.CustomerCreditData.class, CustomerCreditDataProto.CustomerCreditData.Builder.class);
      }

      // Construct using CustomerCreditDataProto.CustomerCreditData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        psptId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        msisdn_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        customerLevel_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        customerAttribue_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        innetDuaration_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        msisdnAmount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        sixMonthFee_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        oweTimes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        expireFlag_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        roamFlagOneYear_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        contractTimes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        callPlace_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        receiveSMSTimes_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        groupFlag_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        billAddress_ = "";
        bitField0_ = (bitField0_ & ~0x00004000);
        customerFeeFlag_ = 0;
        bitField0_ = (bitField0_ & ~0x00008000);
        totalGrade_ = 0;
        bitField0_ = (bitField0_ & ~0x00010000);
        teleGrade_ = 0;
        bitField0_ = (bitField0_ & ~0x00020000);
        basicAttriGrade_ = 0;
        bitField0_ = (bitField0_ & ~0x00040000);
        behaviorGrade_ = 0;
        bitField0_ = (bitField0_ & ~0x00080000);
        creditRelatGrade_ = 0;
        bitField0_ = (bitField0_ & ~0x00100000);
        protocolType_ = 0;
        bitField0_ = (bitField0_ & ~0x00200000);
        contactAmount_ = 0;
        bitField0_ = (bitField0_ & ~0x00400000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CustomerCreditDataProto.internal_static_CustomerCreditData_descriptor;
      }

      public CustomerCreditDataProto.CustomerCreditData getDefaultInstanceForType() {
        return CustomerCreditDataProto.CustomerCreditData.getDefaultInstance();
      }

      public CustomerCreditDataProto.CustomerCreditData build() {
        CustomerCreditDataProto.CustomerCreditData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CustomerCreditDataProto.CustomerCreditData buildPartial() {
        CustomerCreditDataProto.CustomerCreditData result = new CustomerCreditDataProto.CustomerCreditData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.psptId_ = psptId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msisdn_ = msisdn_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.customerLevel_ = customerLevel_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.customerAttribue_ = customerAttribue_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.innetDuaration_ = innetDuaration_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.msisdnAmount_ = msisdnAmount_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.sixMonthFee_ = sixMonthFee_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.oweTimes_ = oweTimes_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.expireFlag_ = expireFlag_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.roamFlagOneYear_ = roamFlagOneYear_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.contractTimes_ = contractTimes_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.callPlace_ = callPlace_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.receiveSMSTimes_ = receiveSMSTimes_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.groupFlag_ = groupFlag_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.billAddress_ = billAddress_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.customerFeeFlag_ = customerFeeFlag_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.totalGrade_ = totalGrade_;
        if (((from_bitField0_ & 0x00020000) == 0x00020000)) {
          to_bitField0_ |= 0x00020000;
        }
        result.teleGrade_ = teleGrade_;
        if (((from_bitField0_ & 0x00040000) == 0x00040000)) {
          to_bitField0_ |= 0x00040000;
        }
        result.basicAttriGrade_ = basicAttriGrade_;
        if (((from_bitField0_ & 0x00080000) == 0x00080000)) {
          to_bitField0_ |= 0x00080000;
        }
        result.behaviorGrade_ = behaviorGrade_;
        if (((from_bitField0_ & 0x00100000) == 0x00100000)) {
          to_bitField0_ |= 0x00100000;
        }
        result.creditRelatGrade_ = creditRelatGrade_;
        if (((from_bitField0_ & 0x00200000) == 0x00200000)) {
          to_bitField0_ |= 0x00200000;
        }
        result.protocolType_ = protocolType_;
        if (((from_bitField0_ & 0x00400000) == 0x00400000)) {
          to_bitField0_ |= 0x00400000;
        }
        result.contactAmount_ = contactAmount_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CustomerCreditDataProto.CustomerCreditData) {
          return mergeFrom((CustomerCreditDataProto.CustomerCreditData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CustomerCreditDataProto.CustomerCreditData other) {
        if (other == CustomerCreditDataProto.CustomerCreditData.getDefaultInstance()) return this;
        if (other.hasPsptId()) {
          bitField0_ |= 0x00000001;
          psptId_ = other.psptId_;
          onChanged();
        }
        if (other.hasMsisdn()) {
          bitField0_ |= 0x00000002;
          msisdn_ = other.msisdn_;
          onChanged();
        }
        if (other.hasCustomerLevel()) {
          bitField0_ |= 0x00000004;
          customerLevel_ = other.customerLevel_;
          onChanged();
        }
        if (other.hasCustomerAttribue()) {
          setCustomerAttribue(other.getCustomerAttribue());
        }
        if (other.hasInnetDuaration()) {
          setInnetDuaration(other.getInnetDuaration());
        }
        if (other.hasMsisdnAmount()) {
          setMsisdnAmount(other.getMsisdnAmount());
        }
        if (other.hasSixMonthFee()) {
          setSixMonthFee(other.getSixMonthFee());
        }
        if (other.hasOweTimes()) {
          setOweTimes(other.getOweTimes());
        }
        if (other.hasExpireFlag()) {
          setExpireFlag(other.getExpireFlag());
        }
        if (other.hasRoamFlagOneYear()) {
          setRoamFlagOneYear(other.getRoamFlagOneYear());
        }
        if (other.hasContractTimes()) {
          setContractTimes(other.getContractTimes());
        }
        if (other.hasCallPlace()) {
          setCallPlace(other.getCallPlace());
        }
        if (other.hasReceiveSMSTimes()) {
          setReceiveSMSTimes(other.getReceiveSMSTimes());
        }
        if (other.hasGroupFlag()) {
          setGroupFlag(other.getGroupFlag());
        }
        if (other.hasBillAddress()) {
          bitField0_ |= 0x00004000;
          billAddress_ = other.billAddress_;
          onChanged();
        }
        if (other.hasCustomerFeeFlag()) {
          setCustomerFeeFlag(other.getCustomerFeeFlag());
        }
        if (other.hasTotalGrade()) {
          setTotalGrade(other.getTotalGrade());
        }
        if (other.hasTeleGrade()) {
          setTeleGrade(other.getTeleGrade());
        }
        if (other.hasBasicAttriGrade()) {
          setBasicAttriGrade(other.getBasicAttriGrade());
        }
        if (other.hasBehaviorGrade()) {
          setBehaviorGrade(other.getBehaviorGrade());
        }
        if (other.hasCreditRelatGrade()) {
          setCreditRelatGrade(other.getCreditRelatGrade());
        }
        if (other.hasProtocolType()) {
          setProtocolType(other.getProtocolType());
        }
        if (other.hasContactAmount()) {
          setContactAmount(other.getContactAmount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPsptId()) {
          
          return false;
        }
        if (!hasMsisdn()) {
          
          return false;
        }
        if (!hasCustomerLevel()) {
          
          return false;
        }
        if (!hasCustomerAttribue()) {
          
          return false;
        }
        if (!hasInnetDuaration()) {
          
          return false;
        }
        if (!hasMsisdnAmount()) {
          
          return false;
        }
        if (!hasSixMonthFee()) {
          
          return false;
        }
        if (!hasOweTimes()) {
          
          return false;
        }
        if (!hasExpireFlag()) {
          
          return false;
        }
        if (!hasRoamFlagOneYear()) {
          
          return false;
        }
        if (!hasContractTimes()) {
          
          return false;
        }
        if (!hasCallPlace()) {
          
          return false;
        }
        if (!hasReceiveSMSTimes()) {
          
          return false;
        }
        if (!hasGroupFlag()) {
          
          return false;
        }
        if (!hasBillAddress()) {
          
          return false;
        }
        if (!hasCustomerFeeFlag()) {
          
          return false;
        }
        if (!hasTotalGrade()) {
          
          return false;
        }
        if (!hasTeleGrade()) {
          
          return false;
        }
        if (!hasBasicAttriGrade()) {
          
          return false;
        }
        if (!hasBehaviorGrade()) {
          
          return false;
        }
        if (!hasCreditRelatGrade()) {
          
          return false;
        }
        if (!hasProtocolType()) {
          
          return false;
        }
        if (!hasContactAmount()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CustomerCreditDataProto.CustomerCreditData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CustomerCreditDataProto.CustomerCreditData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string psptId = 1;
      private java.lang.Object psptId_ = "";
      /**
       * <code>required string psptId = 1;</code>
       *
       * <pre>
       *证件号码；
       * </pre>
       */
      public boolean hasPsptId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string psptId = 1;</code>
       *
       * <pre>
       *证件号码；
       * </pre>
       */
      public java.lang.String getPsptId() {
        java.lang.Object ref = psptId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          psptId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string psptId = 1;</code>
       *
       * <pre>
       *证件号码；
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPsptIdBytes() {
        java.lang.Object ref = psptId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          psptId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string psptId = 1;</code>
       *
       * <pre>
       *证件号码；
       * </pre>
       */
      public Builder setPsptId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        psptId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string psptId = 1;</code>
       *
       * <pre>
       *证件号码；
       * </pre>
       */
      public Builder clearPsptId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        psptId_ = getDefaultInstance().getPsptId();
        onChanged();
        return this;
      }
      /**
       * <code>required string psptId = 1;</code>
       *
       * <pre>
       *证件号码；
       * </pre>
       */
      public Builder setPsptIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        psptId_ = value;
        onChanged();
        return this;
      }

      // required string msisdn = 2;
      private java.lang.Object msisdn_ = "";
      /**
       * <code>required string msisdn = 2;</code>
       *
       * <pre>
       *手机号码
       * </pre>
       */
      public boolean hasMsisdn() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string msisdn = 2;</code>
       *
       * <pre>
       *手机号码
       * </pre>
       */
      public java.lang.String getMsisdn() {
        java.lang.Object ref = msisdn_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          msisdn_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string msisdn = 2;</code>
       *
       * <pre>
       *手机号码
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMsisdnBytes() {
        java.lang.Object ref = msisdn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msisdn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string msisdn = 2;</code>
       *
       * <pre>
       *手机号码
       * </pre>
       */
      public Builder setMsisdn(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msisdn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string msisdn = 2;</code>
       *
       * <pre>
       *手机号码
       * </pre>
       */
      public Builder clearMsisdn() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msisdn_ = getDefaultInstance().getMsisdn();
        onChanged();
        return this;
      }
      /**
       * <code>required string msisdn = 2;</code>
       *
       * <pre>
       *手机号码
       * </pre>
       */
      public Builder setMsisdnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msisdn_ = value;
        onChanged();
        return this;
      }

      // required string customerLevel = 3;
      private java.lang.Object customerLevel_ = "";
      /**
       * <code>required string customerLevel = 3;</code>
       *
       * <pre>
       *用户等级
       * </pre>
       */
      public boolean hasCustomerLevel() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string customerLevel = 3;</code>
       *
       * <pre>
       *用户等级
       * </pre>
       */
      public java.lang.String getCustomerLevel() {
        java.lang.Object ref = customerLevel_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          customerLevel_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string customerLevel = 3;</code>
       *
       * <pre>
       *用户等级
       * </pre>
       */
      public com.google.protobuf.ByteString
          getCustomerLevelBytes() {
        java.lang.Object ref = customerLevel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          customerLevel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string customerLevel = 3;</code>
       *
       * <pre>
       *用户等级
       * </pre>
       */
      public Builder setCustomerLevel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        customerLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string customerLevel = 3;</code>
       *
       * <pre>
       *用户等级
       * </pre>
       */
      public Builder clearCustomerLevel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        customerLevel_ = getDefaultInstance().getCustomerLevel();
        onChanged();
        return this;
      }
      /**
       * <code>required string customerLevel = 3;</code>
       *
       * <pre>
       *用户等级
       * </pre>
       */
      public Builder setCustomerLevelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        customerLevel_ = value;
        onChanged();
        return this;
      }

      // required int32 customerAttribue = 4;
      private int customerAttribue_ ;
      /**
       * <code>required int32 customerAttribue = 4;</code>
       *
       * <pre>
       *客户属性
       * </pre>
       */
      public boolean hasCustomerAttribue() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 customerAttribue = 4;</code>
       *
       * <pre>
       *客户属性
       * </pre>
       */
      public int getCustomerAttribue() {
        return customerAttribue_;
      }
      /**
       * <code>required int32 customerAttribue = 4;</code>
       *
       * <pre>
       *客户属性
       * </pre>
       */
      public Builder setCustomerAttribue(int value) {
        bitField0_ |= 0x00000008;
        customerAttribue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 customerAttribue = 4;</code>
       *
       * <pre>
       *客户属性
       * </pre>
       */
      public Builder clearCustomerAttribue() {
        bitField0_ = (bitField0_ & ~0x00000008);
        customerAttribue_ = 0;
        onChanged();
        return this;
      }

      // required int32 innetDuaration = 5;
      private int innetDuaration_ ;
      /**
       * <code>required int32 innetDuaration = 5;</code>
       *
       * <pre>
       *在网时间，单位：月    
       * </pre>
       */
      public boolean hasInnetDuaration() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 innetDuaration = 5;</code>
       *
       * <pre>
       *在网时间，单位：月    
       * </pre>
       */
      public int getInnetDuaration() {
        return innetDuaration_;
      }
      /**
       * <code>required int32 innetDuaration = 5;</code>
       *
       * <pre>
       *在网时间，单位：月    
       * </pre>
       */
      public Builder setInnetDuaration(int value) {
        bitField0_ |= 0x00000010;
        innetDuaration_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 innetDuaration = 5;</code>
       *
       * <pre>
       *在网时间，单位：月    
       * </pre>
       */
      public Builder clearInnetDuaration() {
        bitField0_ = (bitField0_ & ~0x00000010);
        innetDuaration_ = 0;
        onChanged();
        return this;
      }

      // required int32 msisdnAmount = 6;
      private int msisdnAmount_ ;
      /**
       * <code>required int32 msisdnAmount = 6;</code>
       *
       * <pre>
       *身份证所匹配手机号码数量；
       * </pre>
       */
      public boolean hasMsisdnAmount() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 msisdnAmount = 6;</code>
       *
       * <pre>
       *身份证所匹配手机号码数量；
       * </pre>
       */
      public int getMsisdnAmount() {
        return msisdnAmount_;
      }
      /**
       * <code>required int32 msisdnAmount = 6;</code>
       *
       * <pre>
       *身份证所匹配手机号码数量；
       * </pre>
       */
      public Builder setMsisdnAmount(int value) {
        bitField0_ |= 0x00000020;
        msisdnAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 msisdnAmount = 6;</code>
       *
       * <pre>
       *身份证所匹配手机号码数量；
       * </pre>
       */
      public Builder clearMsisdnAmount() {
        bitField0_ = (bitField0_ & ~0x00000020);
        msisdnAmount_ = 0;
        onChanged();
        return this;
      }

      // required int32 sixMonthFee = 7;
      private int sixMonthFee_ ;
      /**
       * <code>required int32 sixMonthFee = 7;</code>
       *
       * <pre>
       *近六个月月均消费额，单位:分
       * </pre>
       */
      public boolean hasSixMonthFee() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required int32 sixMonthFee = 7;</code>
       *
       * <pre>
       *近六个月月均消费额，单位:分
       * </pre>
       */
      public int getSixMonthFee() {
        return sixMonthFee_;
      }
      /**
       * <code>required int32 sixMonthFee = 7;</code>
       *
       * <pre>
       *近六个月月均消费额，单位:分
       * </pre>
       */
      public Builder setSixMonthFee(int value) {
        bitField0_ |= 0x00000040;
        sixMonthFee_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 sixMonthFee = 7;</code>
       *
       * <pre>
       *近六个月月均消费额，单位:分
       * </pre>
       */
      public Builder clearSixMonthFee() {
        bitField0_ = (bitField0_ & ~0x00000040);
        sixMonthFee_ = 0;
        onChanged();
        return this;
      }

      // required int32 oweTimes = 8;
      private int oweTimes_ ;
      /**
       * <code>required int32 oweTimes = 8;</code>
       *
       * <pre>
       *近六个月内逾期欠费次数
       * </pre>
       */
      public boolean hasOweTimes() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required int32 oweTimes = 8;</code>
       *
       * <pre>
       *近六个月内逾期欠费次数
       * </pre>
       */
      public int getOweTimes() {
        return oweTimes_;
      }
      /**
       * <code>required int32 oweTimes = 8;</code>
       *
       * <pre>
       *近六个月内逾期欠费次数
       * </pre>
       */
      public Builder setOweTimes(int value) {
        bitField0_ |= 0x00000080;
        oweTimes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 oweTimes = 8;</code>
       *
       * <pre>
       *近六个月内逾期欠费次数
       * </pre>
       */
      public Builder clearOweTimes() {
        bitField0_ = (bitField0_ & ~0x00000080);
        oweTimes_ = 0;
        onChanged();
        return this;
      }

      // required int32 expireFlag = 9;
      private int expireFlag_ ;
      /**
       * <code>required int32 expireFlag = 9;</code>
       *
       * <pre>
       *当前是否逾期欠费
       * </pre>
       */
      public boolean hasExpireFlag() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required int32 expireFlag = 9;</code>
       *
       * <pre>
       *当前是否逾期欠费
       * </pre>
       */
      public int getExpireFlag() {
        return expireFlag_;
      }
      /**
       * <code>required int32 expireFlag = 9;</code>
       *
       * <pre>
       *当前是否逾期欠费
       * </pre>
       */
      public Builder setExpireFlag(int value) {
        bitField0_ |= 0x00000100;
        expireFlag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 expireFlag = 9;</code>
       *
       * <pre>
       *当前是否逾期欠费
       * </pre>
       */
      public Builder clearExpireFlag() {
        bitField0_ = (bitField0_ & ~0x00000100);
        expireFlag_ = 0;
        onChanged();
        return this;
      }

      // required int32 roamFlagOneYear = 10;
      private int roamFlagOneYear_ ;
      /**
       * <code>required int32 roamFlagOneYear = 10;</code>
       *
       * <pre>
       *近1年内是否有境外漫游记录
       * </pre>
       */
      public boolean hasRoamFlagOneYear() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required int32 roamFlagOneYear = 10;</code>
       *
       * <pre>
       *近1年内是否有境外漫游记录
       * </pre>
       */
      public int getRoamFlagOneYear() {
        return roamFlagOneYear_;
      }
      /**
       * <code>required int32 roamFlagOneYear = 10;</code>
       *
       * <pre>
       *近1年内是否有境外漫游记录
       * </pre>
       */
      public Builder setRoamFlagOneYear(int value) {
        bitField0_ |= 0x00000200;
        roamFlagOneYear_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 roamFlagOneYear = 10;</code>
       *
       * <pre>
       *近1年内是否有境外漫游记录
       * </pre>
       */
      public Builder clearRoamFlagOneYear() {
        bitField0_ = (bitField0_ & ~0x00000200);
        roamFlagOneYear_ = 0;
        onChanged();
        return this;
      }

      // required int32 contractTimes = 11;
      private int contractTimes_ ;
      /**
       * <code>required int32 contractTimes = 11;</code>
       *
       * <pre>
       *与指定号码联系次数；
       * </pre>
       */
      public boolean hasContractTimes() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>required int32 contractTimes = 11;</code>
       *
       * <pre>
       *与指定号码联系次数；
       * </pre>
       */
      public int getContractTimes() {
        return contractTimes_;
      }
      /**
       * <code>required int32 contractTimes = 11;</code>
       *
       * <pre>
       *与指定号码联系次数；
       * </pre>
       */
      public Builder setContractTimes(int value) {
        bitField0_ |= 0x00000400;
        contractTimes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 contractTimes = 11;</code>
       *
       * <pre>
       *与指定号码联系次数；
       * </pre>
       */
      public Builder clearContractTimes() {
        bitField0_ = (bitField0_ & ~0x00000400);
        contractTimes_ = 0;
        onChanged();
        return this;
      }

      // required int32 callPlace = 12;
      private int callPlace_ ;
      /**
       * <code>required int32 callPlace = 12;</code>
       *
       * <pre>
       *白天常用通话地区,维表方式提供
       * </pre>
       */
      public boolean hasCallPlace() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>required int32 callPlace = 12;</code>
       *
       * <pre>
       *白天常用通话地区,维表方式提供
       * </pre>
       */
      public int getCallPlace() {
        return callPlace_;
      }
      /**
       * <code>required int32 callPlace = 12;</code>
       *
       * <pre>
       *白天常用通话地区,维表方式提供
       * </pre>
       */
      public Builder setCallPlace(int value) {
        bitField0_ |= 0x00000800;
        callPlace_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 callPlace = 12;</code>
       *
       * <pre>
       *白天常用通话地区,维表方式提供
       * </pre>
       */
      public Builder clearCallPlace() {
        bitField0_ = (bitField0_ & ~0x00000800);
        callPlace_ = 0;
        onChanged();
        return this;
      }

      // required int32 receiveSMSTimes = 13;
      private int receiveSMSTimes_ ;
      /**
       * <code>required int32 receiveSMSTimes = 13;</code>
       *
       * <pre>
       * 指定号码短信接受次数
       * </pre>
       */
      public boolean hasReceiveSMSTimes() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>required int32 receiveSMSTimes = 13;</code>
       *
       * <pre>
       * 指定号码短信接受次数
       * </pre>
       */
      public int getReceiveSMSTimes() {
        return receiveSMSTimes_;
      }
      /**
       * <code>required int32 receiveSMSTimes = 13;</code>
       *
       * <pre>
       * 指定号码短信接受次数
       * </pre>
       */
      public Builder setReceiveSMSTimes(int value) {
        bitField0_ |= 0x00001000;
        receiveSMSTimes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 receiveSMSTimes = 13;</code>
       *
       * <pre>
       * 指定号码短信接受次数
       * </pre>
       */
      public Builder clearReceiveSMSTimes() {
        bitField0_ = (bitField0_ & ~0x00001000);
        receiveSMSTimes_ = 0;
        onChanged();
        return this;
      }

      // required int32 groupFlag = 14;
      private int groupFlag_ ;
      /**
       * <code>required int32 groupFlag = 14;</code>
       *
       * <pre>
       * 是否为联通集团客户
       * </pre>
       */
      public boolean hasGroupFlag() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>required int32 groupFlag = 14;</code>
       *
       * <pre>
       * 是否为联通集团客户
       * </pre>
       */
      public int getGroupFlag() {
        return groupFlag_;
      }
      /**
       * <code>required int32 groupFlag = 14;</code>
       *
       * <pre>
       * 是否为联通集团客户
       * </pre>
       */
      public Builder setGroupFlag(int value) {
        bitField0_ |= 0x00002000;
        groupFlag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 groupFlag = 14;</code>
       *
       * <pre>
       * 是否为联通集团客户
       * </pre>
       */
      public Builder clearGroupFlag() {
        bitField0_ = (bitField0_ & ~0x00002000);
        groupFlag_ = 0;
        onChanged();
        return this;
      }

      // required string billAddress = 15;
      private java.lang.Object billAddress_ = "";
      /**
       * <code>required string billAddress = 15;</code>
       *
       * <pre>
       * 联通账单地址
       * </pre>
       */
      public boolean hasBillAddress() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>required string billAddress = 15;</code>
       *
       * <pre>
       * 联通账单地址
       * </pre>
       */
      public java.lang.String getBillAddress() {
        java.lang.Object ref = billAddress_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          billAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string billAddress = 15;</code>
       *
       * <pre>
       * 联通账单地址
       * </pre>
       */
      public com.google.protobuf.ByteString
          getBillAddressBytes() {
        java.lang.Object ref = billAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          billAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string billAddress = 15;</code>
       *
       * <pre>
       * 联通账单地址
       * </pre>
       */
      public Builder setBillAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        billAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string billAddress = 15;</code>
       *
       * <pre>
       * 联通账单地址
       * </pre>
       */
      public Builder clearBillAddress() {
        bitField0_ = (bitField0_ & ~0x00004000);
        billAddress_ = getDefaultInstance().getBillAddress();
        onChanged();
        return this;
      }
      /**
       * <code>required string billAddress = 15;</code>
       *
       * <pre>
       * 联通账单地址
       * </pre>
       */
      public Builder setBillAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        billAddress_ = value;
        onChanged();
        return this;
      }

      // required int32 CustomerFeeFlag = 16;
      private int customerFeeFlag_ ;
      /**
       * <code>required int32 CustomerFeeFlag = 16;</code>
       *
       * <pre>
       * 客户属性标识
       * </pre>
       */
      public boolean hasCustomerFeeFlag() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>required int32 CustomerFeeFlag = 16;</code>
       *
       * <pre>
       * 客户属性标识
       * </pre>
       */
      public int getCustomerFeeFlag() {
        return customerFeeFlag_;
      }
      /**
       * <code>required int32 CustomerFeeFlag = 16;</code>
       *
       * <pre>
       * 客户属性标识
       * </pre>
       */
      public Builder setCustomerFeeFlag(int value) {
        bitField0_ |= 0x00008000;
        customerFeeFlag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 CustomerFeeFlag = 16;</code>
       *
       * <pre>
       * 客户属性标识
       * </pre>
       */
      public Builder clearCustomerFeeFlag() {
        bitField0_ = (bitField0_ & ~0x00008000);
        customerFeeFlag_ = 0;
        onChanged();
        return this;
      }

      // required int32 totalGrade = 17;
      private int totalGrade_ ;
      /**
       * <code>required int32 totalGrade = 17;</code>
       *
       * <pre>
       *总评分
       * </pre>
       */
      public boolean hasTotalGrade() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      /**
       * <code>required int32 totalGrade = 17;</code>
       *
       * <pre>
       *总评分
       * </pre>
       */
      public int getTotalGrade() {
        return totalGrade_;
      }
      /**
       * <code>required int32 totalGrade = 17;</code>
       *
       * <pre>
       *总评分
       * </pre>
       */
      public Builder setTotalGrade(int value) {
        bitField0_ |= 0x00010000;
        totalGrade_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 totalGrade = 17;</code>
       *
       * <pre>
       *总评分
       * </pre>
       */
      public Builder clearTotalGrade() {
        bitField0_ = (bitField0_ & ~0x00010000);
        totalGrade_ = 0;
        onChanged();
        return this;
      }

      // required int32 teleGrade = 18;
      private int teleGrade_ ;
      /**
       * <code>required int32 teleGrade = 18;</code>
       *
       * <pre>
       *通信业务特征评分
       * </pre>
       */
      public boolean hasTeleGrade() {
        return ((bitField0_ & 0x00020000) == 0x00020000);
      }
      /**
       * <code>required int32 teleGrade = 18;</code>
       *
       * <pre>
       *通信业务特征评分
       * </pre>
       */
      public int getTeleGrade() {
        return teleGrade_;
      }
      /**
       * <code>required int32 teleGrade = 18;</code>
       *
       * <pre>
       *通信业务特征评分
       * </pre>
       */
      public Builder setTeleGrade(int value) {
        bitField0_ |= 0x00020000;
        teleGrade_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 teleGrade = 18;</code>
       *
       * <pre>
       *通信业务特征评分
       * </pre>
       */
      public Builder clearTeleGrade() {
        bitField0_ = (bitField0_ & ~0x00020000);
        teleGrade_ = 0;
        onChanged();
        return this;
      }

      // required int32 basicAttriGrade = 19;
      private int basicAttriGrade_ ;
      /**
       * <code>required int32 basicAttriGrade = 19;</code>
       *
       * <pre>
       *用户基本特征评分
       * </pre>
       */
      public boolean hasBasicAttriGrade() {
        return ((bitField0_ & 0x00040000) == 0x00040000);
      }
      /**
       * <code>required int32 basicAttriGrade = 19;</code>
       *
       * <pre>
       *用户基本特征评分
       * </pre>
       */
      public int getBasicAttriGrade() {
        return basicAttriGrade_;
      }
      /**
       * <code>required int32 basicAttriGrade = 19;</code>
       *
       * <pre>
       *用户基本特征评分
       * </pre>
       */
      public Builder setBasicAttriGrade(int value) {
        bitField0_ |= 0x00040000;
        basicAttriGrade_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 basicAttriGrade = 19;</code>
       *
       * <pre>
       *用户基本特征评分
       * </pre>
       */
      public Builder clearBasicAttriGrade() {
        bitField0_ = (bitField0_ & ~0x00040000);
        basicAttriGrade_ = 0;
        onChanged();
        return this;
      }

      // required int32 behaviorGrade = 20;
      private int behaviorGrade_ ;
      /**
       * <code>required int32 behaviorGrade = 20;</code>
       *
       * <pre>
       *用户行为特征评分
       * </pre>
       */
      public boolean hasBehaviorGrade() {
        return ((bitField0_ & 0x00080000) == 0x00080000);
      }
      /**
       * <code>required int32 behaviorGrade = 20;</code>
       *
       * <pre>
       *用户行为特征评分
       * </pre>
       */
      public int getBehaviorGrade() {
        return behaviorGrade_;
      }
      /**
       * <code>required int32 behaviorGrade = 20;</code>
       *
       * <pre>
       *用户行为特征评分
       * </pre>
       */
      public Builder setBehaviorGrade(int value) {
        bitField0_ |= 0x00080000;
        behaviorGrade_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 behaviorGrade = 20;</code>
       *
       * <pre>
       *用户行为特征评分
       * </pre>
       */
      public Builder clearBehaviorGrade() {
        bitField0_ = (bitField0_ & ~0x00080000);
        behaviorGrade_ = 0;
        onChanged();
        return this;
      }

      // required int32 creditRelatGrade = 21;
      private int creditRelatGrade_ ;
      /**
       * <code>required int32 creditRelatGrade = 21;</code>
       *
       * <pre>
       *信用关联特征的评分
       * </pre>
       */
      public boolean hasCreditRelatGrade() {
        return ((bitField0_ & 0x00100000) == 0x00100000);
      }
      /**
       * <code>required int32 creditRelatGrade = 21;</code>
       *
       * <pre>
       *信用关联特征的评分
       * </pre>
       */
      public int getCreditRelatGrade() {
        return creditRelatGrade_;
      }
      /**
       * <code>required int32 creditRelatGrade = 21;</code>
       *
       * <pre>
       *信用关联特征的评分
       * </pre>
       */
      public Builder setCreditRelatGrade(int value) {
        bitField0_ |= 0x00100000;
        creditRelatGrade_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 creditRelatGrade = 21;</code>
       *
       * <pre>
       *信用关联特征的评分
       * </pre>
       */
      public Builder clearCreditRelatGrade() {
        bitField0_ = (bitField0_ & ~0x00100000);
        creditRelatGrade_ = 0;
        onChanged();
        return this;
      }

      // required int32 protocolType = 22;
      private int protocolType_ ;
      /**
       * <code>required int32 protocolType = 22;</code>
       *
       * <pre>
       * 协议类型
       * </pre>
       */
      public boolean hasProtocolType() {
        return ((bitField0_ & 0x00200000) == 0x00200000);
      }
      /**
       * <code>required int32 protocolType = 22;</code>
       *
       * <pre>
       * 协议类型
       * </pre>
       */
      public int getProtocolType() {
        return protocolType_;
      }
      /**
       * <code>required int32 protocolType = 22;</code>
       *
       * <pre>
       * 协议类型
       * </pre>
       */
      public Builder setProtocolType(int value) {
        bitField0_ |= 0x00200000;
        protocolType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 protocolType = 22;</code>
       *
       * <pre>
       * 协议类型
       * </pre>
       */
      public Builder clearProtocolType() {
        bitField0_ = (bitField0_ & ~0x00200000);
        protocolType_ = 0;
        onChanged();
        return this;
      }

      // required int32 contactAmount = 23;
      private int contactAmount_ ;
      /**
       * <code>required int32 contactAmount = 23;</code>
       *
       * <pre>
       * 前一个月呼入及呼出联络圈
       * </pre>
       */
      public boolean hasContactAmount() {
        return ((bitField0_ & 0x00400000) == 0x00400000);
      }
      /**
       * <code>required int32 contactAmount = 23;</code>
       *
       * <pre>
       * 前一个月呼入及呼出联络圈
       * </pre>
       */
      public int getContactAmount() {
        return contactAmount_;
      }
      /**
       * <code>required int32 contactAmount = 23;</code>
       *
       * <pre>
       * 前一个月呼入及呼出联络圈
       * </pre>
       */
      public Builder setContactAmount(int value) {
        bitField0_ |= 0x00400000;
        contactAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 contactAmount = 23;</code>
       *
       * <pre>
       * 前一个月呼入及呼出联络圈
       * </pre>
       */
      public Builder clearContactAmount() {
        bitField0_ = (bitField0_ & ~0x00400000);
        contactAmount_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CustomerCreditData)
    }

    static {
      defaultInstance = new CustomerCreditData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CustomerCreditData)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CustomerCreditData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CustomerCreditData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017attribute.proto\"\211\004\n\022CustomerCreditData" +
      "\022\016\n\006psptId\030\001 \002(\t\022\016\n\006msisdn\030\002 \002(\t\022\025\n\rcust" +
      "omerLevel\030\003 \002(\t\022\030\n\020customerAttribue\030\004 \002(" +
      "\005\022\026\n\016innetDuaration\030\005 \002(\005\022\024\n\014msisdnAmoun" +
      "t\030\006 \002(\005\022\023\n\013sixMonthFee\030\007 \002(\005\022\020\n\010oweTimes" +
      "\030\010 \002(\005\022\022\n\nexpireFlag\030\t \002(\005\022\027\n\017roamFlagOn" +
      "eYear\030\n \002(\005\022\025\n\rcontractTimes\030\013 \002(\005\022\021\n\tca" +
      "llPlace\030\014 \002(\005\022\027\n\017receiveSMSTimes\030\r \002(\005\022\021" +
      "\n\tgroupFlag\030\016 \002(\005\022\023\n\013billAddress\030\017 \002(\t\022\027" +
      "\n\017CustomerFeeFlag\030\020 \002(\005\022\022\n\ntotalGrade\030\021 ",
      "\002(\005\022\021\n\tteleGrade\030\022 \002(\005\022\027\n\017basicAttriGrad" +
      "e\030\023 \002(\005\022\025\n\rbehaviorGrade\030\024 \002(\005\022\030\n\020credit" +
      "RelatGrade\030\025 \002(\005\022\024\n\014protocolType\030\026 \002(\005\022\025" +
      "\n\rcontactAmount\030\027 \002(\005BC\n(com.huawei.are." +
      "algorithm.Credit.BankOfSHB\027CustomerCredi" +
      "tDataProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_CustomerCreditData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_CustomerCreditData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CustomerCreditData_descriptor,
              new java.lang.String[] { "PsptId", "Msisdn", "CustomerLevel", "CustomerAttribue", "InnetDuaration", "MsisdnAmount", "SixMonthFee", "OweTimes", "ExpireFlag", "RoamFlagOneYear", "ContractTimes", "CallPlace", "ReceiveSMSTimes", "GroupFlag", "BillAddress", "CustomerFeeFlag", "TotalGrade", "TeleGrade", "BasicAttriGrade", "BehaviorGrade", "CreditRelatGrade", "ProtocolType", "ContactAmount", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
