
package demo.webservice.rhzx;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CreditReportServiceDelegate", targetNamespace = "http://webservice.icrqs.cfcc.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CreditReportServiceDelegate {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.cfcc.icrqs.webservice.CuResult
     */
    @WebMethod
    @WebResult(partName = "return")
    public CuResult sendCuRequest(
        @WebParam(name = "arg0", partName = "arg0")
        CuSingleRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.cfcc.icrqs.webservice.CuSingleResult
     */
    @WebMethod
    @WebResult(partName = "return")
    public CuSingleResult getCuResult(
        @WebParam(name = "arg0", partName = "arg0")
        CuGetResult arg0);

}
