
package demo.webservice.rhzx;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebServiceClient(name = "CreditReportService", targetNamespace = "http://webservice.icrqs.cfcc.com/", wsdlLocation = "http://10.240.91.32:7001/icrqs/CreditReportService?wsdl")
public class CreditReportService extends Service {

	private final static URL CREDITREPORTSERVICE_WSDL_LOCATION;
	private final static WebServiceException CREDITREPORTSERVICE_EXCEPTION;
	private final static QName CREDITREPORTSERVICE_QNAME = new QName("http://webservice.icrqs.cfcc.com/",
			"CreditReportService");

	static {
		URL url = null;
		WebServiceException e = null;
		try {
			url = new URL("http://10.240.91.32:7001/icrqs/CreditReportService?wsdl");
		} catch (MalformedURLException ex) {
			e = new WebServiceException(ex);
		}
		CREDITREPORTSERVICE_WSDL_LOCATION = url;
		CREDITREPORTSERVICE_EXCEPTION = e;
	}

	public CreditReportService() {
		super(__getWsdlLocation(), CREDITREPORTSERVICE_QNAME);
	}

	public CreditReportService(WebServiceFeature... features) {
		super(__getWsdlLocation(), CREDITREPORTSERVICE_QNAME, features);
	}

	public CreditReportService(URL wsdlLocation) {
		super(wsdlLocation, CREDITREPORTSERVICE_QNAME);
	}

	public CreditReportService(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, CREDITREPORTSERVICE_QNAME, features);
	}

	public CreditReportService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public CreditReportService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 * 
	 * @return returns CreditReportServiceDelegate
	 */
	@WebEndpoint(name = "CreditReportServicePort")
	public CreditReportServiceDelegate getCreditReportServicePort() {
		return super.getPort(new QName("http://webservice.icrqs.cfcc.com/", "CreditReportServicePort"),
				CreditReportServiceDelegate.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns CreditReportServiceDelegate
	 */
	@WebEndpoint(name = "CreditReportServicePort")
	public CreditReportServiceDelegate getCreditReportServicePort(WebServiceFeature... features) {
		return super.getPort(new QName("http://webservice.icrqs.cfcc.com/", "CreditReportServicePort"),
				CreditReportServiceDelegate.class, features);
	}

	private static URL __getWsdlLocation() {
		if (CREDITREPORTSERVICE_EXCEPTION != null) {
			throw CREDITREPORTSERVICE_EXCEPTION;
		}
		return CREDITREPORTSERVICE_WSDL_LOCATION;
	}

}
